{
 "title": "comp",
 "time": { "from": "2024-01-03T22:07:20.191Z", "to": "2024-01-03T22:16:34.593Z" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date, overall_compatibility, career_compatibility, love_compatibility, feelings_compatibility FROM compatibility_results LIMIT 50 "
    }
   ]
  },
  {
   "title": "overall_compatibility",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT overall_compatibility FROM compatibility_results LIMIT 50 "
    }
   ]
  },
  {
   "title": "love_compatibility",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT love_compatibility FROM compatibility_results LIMIT 50 "
    }
   ]
  },
  {
   "title": "career_compatibility",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT career_compatibility FROM compatibility_results LIMIT 50 "
    }
   ]
  },
  {
   "title": "feelings_compatibility",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT feelings_compatibility FROM compatibility_results LIMIT 50 "
    }
   ]
  }
 ]
}